### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Poliwrath** [rumoi/ruri#3]
Hi, is there a specific code style / formatting to follow?

**Comment by Poliwrath** [comment]
Also, are there any reasonings for:

* A majority of the server being in one file
* Unnecessary comments such as ```std::to_string(s.countGeki);//count geki```
* Not using a already-existing HTTP webserver/library
* Port selection (420 & 421)

**Comment by rumoi** [comment]
It is in one file as that is just how I like to organize things (ctrl f is better in a single file)

The geki comment was written before the actual line was written.

Why would I use it? If I did there would be heaps of useless (slow) auto handling. As an example I want to only pass the raw (still chunked) http request from the osu server/ direct mirror where I am just passing it directly back to the client. The client will unchunk the data, offloading the memory allocations to the users.

The port numbers were just a meme for the temporary windows build - You should really be building ruri on GCC with the flag LINUX which does not even use ports.

**Comment by Poliwrath** [comment]
>ctrl f is better in a single file

Ctrl+Shift+F? Though I'm not sure which IDE you're using, that key combination opens the "Find in Files" menu in Visual Studio.

>Why would I use it

Security, performance? I'm not sure if yours has been audited or even fuzz tested.

>there would be heaps of useless (slow) auto handling

Have you benchmarked it? I doubt it would be adding more than a few thousand nanoseconds, which shouldn't matter.

**Comment by rumoi** [comment]
Find in files is slow and inconsistent.

 I doubt security is a problem with a simple tcp request. Im only sending outbound connections to trusted sources (all inbound requests are not direct connections - all inbound requests are connections with nginx). Performance is an issue and a directive in software designed to run as a server.

As stated in your second question it does matter.

**Comment by Poliwrath** [comment]
>all inbound requests are connections with nginx

Oh, I'm an idiot then -- I wasn't too sure how the server was configured.

Since you seem to be aware of UNIX sockets existing, why not use them (named pipes on Windows) for the MySQL connection?

**Comment by rumoi** [comment]
I am planning on ditching the MySQL connectors library with my own implementation when I get the time. In general SQL is relatively rarely called in time critical operations.

**Comment by Poliwrath** [comment]
Ok

**Comment by spook0** [comment]
Ok

**Comment by lukeacat** [comment]
ok

**Comment by Poliwrath** [comment]
Air
by shiki
Enjoy the cool air out on the
