### ISSUE TITLE
Commands are buggy

### ISSUE THREAD

**Issue by hazel0177** [rumoi/ruri#5]
Let me know if this is the right repo to open this issue to, but while playing on Akatsuki, I noticed that roll appears to be broken? If this is only a thing on the akatsuki repo, let me know and i'll close.

![image](https://user-images.githubusercontent.com/42550681/61413728-2481b180-a8e4-11e9-86b1-58537b58c3db.png)

**Comment by rumoi** [comment]
Imagine genuinely thinking a feature is a bug.

**Comment by cyanidee** [comment]
i laughed hard, gg
