### ISSUE TITLE
REQUEST: Makefile

### ISSUE THREAD

**Issue by Kreyren** [rumoi/ruri#9]
Requesting makefile adaptation so that ruri could be compiled using gcc easily instead of messing with `cmake` and frankenstaining Visual Studio Solution files on linux.

**Comment by depreciate** [comment]
it can already be compiled using gcc

**Comment by rumoi** [comment]
Hey. I personally do not like cmake or any type of build manager for that case. I am also currently on the fence about future windows support. At this point ruri should be compiled exclusively with g++/clang with the LINUX flag - Unix sockets are much better.

I am planning on writing my own SQL client which would remove the need for all libraries entirely allowing for easier compile parameters while also allowing the compiler to go for more aggressive optimizations.

As for now you will have to download the proper mysqlconnector library files and install the mysqlcon dev package.

['Linux - Generic' should work for most cases](https://dev.mysql.com/downloads/connector/cpp/)

```
sudo apt-get install libmysqlcppconn-dev
```

```
g++-9 -std=c++17 lz4.c *cpp BCrypt/*c -D LINUX -I pathtosql/mysql/include -pthread -lmysqlcppconn -w -march=native -O2
```

**Comment by Kreyren** [comment]
On https://github.com/rumoi/ruri/commit/49c90e41bc9e922fb4d56e2200d104923e8e39f0

aptli: http://ix.io/1Ugk (note `libmysqlcppconn-dev` installed)

![image](https://user-images.githubusercontent.com/11302521/64275559-5b179800-cf35-11e9-82a4-947bfeb13c8a.png)

Results in:

```console
root@debian:/usr/src/ruri/ruri# ls
Achievement.h  Base64.h    Connection.h  lz4.c	  ruri_API.h		SQL.h
aes.cpp        BCrypt	   cpp.hint	 Match.h  ruri.vcxproj
aes.h	       Channel.h   Linux.h	 oppai.h  ruri.vcxproj.filters
Aria.h	       Commands.h  LZ4		 pp	  Source.cpp
root@debian:/usr/src/ruri/ruri# g++-9 -std=c++17 lz4.c *cpp BCrypt/*c -D LINUX -I pathtosql/mysql/include -pthread -lmysqlcppconn -w -march=native -O2
In file included from Source.cpp:484:
SQL.h:5:10: fatal error: jdbc/cppconn/connection.h: No such file or directory
    5 | #include <jdbc/cppconn/connection.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
root@debian:/usr/src/ruri/ruri# 
```

Same issue on https://github.com/rumoi/ruri/commit/7be02c8aebdefe9719900f3dbc1bd9a94f69f683

## SELF-DIAG

**Disclaimer**: i'm not sure if this is sufficient fix so i won't be making MR

`libmysqlcppconn-dev` provides only `/usr/include/cppconn` where `/usr/include/jdbc/cppconn` **seems** to be expected -> Assuming source issue instead of frankenstaining system.

```
root@debian:/usr/src/ruri/ruri# g++-9 -std=c++17 lz4.c *cpp BCrypt/*c -D LINUX -I pathtosql/mysql/include -pthread -lmysqlcppconn -w -march=native -O2
root@debian:/usr/src/ruri/ruri# 
```

Seems to compile if SQL.h is changed on 
```cpp
#include <cppconn/connection.h>
#include <cppconn/driver.h>
#include <cppconn/exception.h>
#include <cppconn/resultset.h>
#include <cppconn/statement.h>
```

```
root@debian:/usr/src/ruri/ruri# ls -la /usr/include/cppconn/
total 96
drwxr-xr-x 2 root root   360 Sep  4 16:56 .
drwxr-xr-x 1 root root   900 Sep  4 16:56 ..
-rw-r--r-- 1 root root  2090 Jan 16  2019 build_config.h
-rw-r--r-- 1 root root  3185 Aug 14 08:09 config.h
-rw-r--r-- 1 root root  5125 Jan 16  2019 connection.h
-rw-r--r-- 1 root root  1955 Jan 16  2019 datatype.h
-rw-r--r-- 1 root root  2471 Jan 16  2019 driver.h
-rw-r--r-- 1 root root  5693 Aug 14 08:09 exception.h
-rw-r--r-- 1 root root 14865 Jan 16  2019 metadata.h
-rw-r--r-- 1 root root  2423 Jan 16  2019 parameter_metadata.h
-rw-r--r-- 1 root root  3252 Jan 16  2019 prepared_statement.h
-rw-r--r-- 1 root root  4927 Jan 16  2019 resultset.h
-rw-r--r-- 1 root root  3223 Jan 16  2019 resultset_metadata.h
-rw-r--r-- 1 root root  6222 Jan 16  2019 sqlstring.h
-rw-r--r-- 1 root root  2888 Jan 16  2019 statement.h
-rw-r--r-- 1 root root  7603 Jan 16  2019 variant.h
-rw-r--r-- 1 root root  1960 Aug 14 08:09 version_info.h
-rw-r--r-- 1 root root  2292 Jan 16  2019 warning.h
```

**Comment by depreciate** [comment]
pathtosql/mysql/include

**Comment by Kreyren** [comment]
@depreciate elaborate?

**Comment by jacksonisiah** [comment]
@Kreyren can you not read? change that to your path for your mysql
connector. don't copy paste without looking

>

**Comment by Kreyren** [comment]
@jacksonisiah figured that much, but why is it required to point to mysql when @rumoi recommended `libmysqlcppconn-dev` which store it's files in `/usr/include/cppconn` ?

\+ proposed path doesn't have required files
```console
user@debian:~$ ls /usr/include/mysql/
errmsg.h           mariadb_ctype.h    my_config.h        mysql.h
ma_list.h          mariadb_dyncol.h   my_global.h        mysql_version.h
ma_pvio.h          mariadb_stmt.h     mysql/             my_sys.h
mariadb/           mariadb_version.h  mysql_com.h        server/
mariadb_com.h      ma_tls.h           mysqld_error.h  
```

EDIT: my bad

g++-9 -std=c++17 lz4.c *cpp BCrypt/*c -D LINUX -I **pathtosql/mysql/include** -pthread -lmysqlcppconn -w -march=native -O2

EDIT2: Where is  **pathtosql/mysql/include** ? Is `/usr/include/mysql/` expected ?

**Comment by depreciate** [comment]
hey dumb fuck you replace it with the path.

**Comment by Kreyren** [comment]
> hey dumb fuck you replace it with the path.

path to where? `/usr/include/mysql` ?

**Comment by ilsubyeega** [comment]
> 
> 
> > hey dumb fuck you replace it with the path.
> 
> path to where? `/usr/include/mysql` ?

![image](https://user-images.githubusercontent.com/37479424/64423876-796ec680-d0e2-11e9-9a18-02e373fa1583.png)

**Comment by jacksonisiah** [comment]
if you're not able to figure this out you probably shouldn't be messing
with it, because it's really simple to understand...

put the connector somewhere in your ruri directory and replace that with
the path for it iirc.

>

**Comment by Kreyren** [comment]
> if you're not able to figure this out you probably shouldn't be messing with it, because it's really simple to understand...

Doubt it being simple to understand assuming there multiple entries for `*sql*`
`Search for sql in buster/amd64: [truncated] mariadb-server-10.3: etc/default/mysql; postgresql-common: etc/apt/apt.conf.d/01autoremove-postgresql; python-othman: usr/share/othman/quran.sql, usr/share/othman/update-othmani.sql; apparmor: etc/apparmor.d/abstractions/mysql; bacula-director: etc/bacula/scripts/query.sql; freeradius-config: etc/freeradius/3.0/mods-available/abfab_psk_sql, etc/freeradius/3.0/mods-available/sql, etc/freeradius/3.0/mods-config/sql/cui/mysql/schema.sql, etc/freeradius/3.0/mods-config/sql/cui/postgresql/schema.sql, etc/freeradius/3.0/mods-config/sql/cui/sqlite/schema.sql, etc/freeradius/3.0/mods-config/sql/ippool-dhcp/mysql/schema.sql, etc/freeradius/3.0/mods-config/sql/ippool-dhcp/oracle/schema.sql, etc/freeradius/3.0/mods-config/sql/ippool-...`

and i'm trying to get confirmation for library used to exclude unnecessary variables from debugging.. 

So far it seems that provided path is sufficient with changes to `Source.cpp` for port listening with ripple db and hanayo for frontend.

>  put the connector somewhere in your ruri directory and replace that with the path for it iirc.

Elaborate? `SQL.h` points to `/usr/include/cppconn` placing it in root of ruri/ruri woudn't work afaik

**Comment by hazel0177** [comment]
@rumoi close this

**Comment by rumoi** [comment]
You had to download and extract the sql files I sent in my first post. Then set that path to where you extracted it. The original include works on both windows and linux but as I stated before I might drop windows support later so in the future it might be the <> include - but at that I might not even use that mysql connector.

**Comment by Kreyren** [comment]
thanks for info
